[package]
name = "branec_parser"
version = "0.1.0"
edition = "2024"

[dependencies]
branec_source = { path = "../branec_source/" }
brane_core = { path = "../../runtime/brane_core/" }
chumsky.workspace = true
